---
name: PrivacyPass Challenge Extension

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    name: Running on Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 16]
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Building
        run: npm run build
      - name: Testing
        run: npm test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./dist
